baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Stellaris'

[params]
  description = 'Writing about things I build and explore.'

[taxonomies]
  tag = 'tags'

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = false
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
